# generated by datamodel-codegen:
#   filename:  api.yml
#   timestamp: 2024-12-25T11:13:07+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel


class Profile(BaseModel):
    username: Optional[str] = Field(None, examples=["username"])
    friendly_name: Optional[str] = Field(None, examples=["friendly_name"])
    student_id: Optional[str] = Field(
        None, description="学号或工号", examples=["520030910001"]
    )


class Example(BaseModel):
    name: Optional[str] = Field(None, description="样例名称")
    input: Optional[str] = Field(None, description="输入")
    output: Optional[str] = Field(None, description="输出")
    description: Optional[str] = Field(None, description="样例描述")


class ProblemBrief(BaseModel):
    id: Optional[int] = Field(None, examples=[1000])
    title: Optional[str] = Field(
        None, description="题目未发布时此项为 null", examples=["A+B"]
    )
    url: Optional[str] = Field(
        None,
        description="题目未发布时此项为 null",
        examples=["/OnlineJudge/api/v1/problem/42"],
    )
    submit_url: Optional[str] = Field(
        None,
        description="题目未发布时此项为 null",
        examples=["/OnlineJudge/api/v1/problem/42/submit"],
    )
    html_url: Optional[str] = Field(
        None,
        description="题目未发布时此项为 null",
        examples=["/OnlineJudge/problem/42"],
    )


class CourseTag(BaseModel):
    id: Optional[int] = Field(None, examples=[42])
    name: Optional[str] = None


class Term(BaseModel):
    id: Optional[int] = Field(None, examples=[42])
    name: Optional[str] = None
    start_time: Optional[datetime] = None
    end_time: Optional[datetime] = None


class Course(BaseModel):
    id: Optional[int] = Field(None, examples=[42])
    name: Optional[str] = None
    description: Optional[str] = None
    tag: Optional[CourseTag] = None
    term: Optional[Term] = None
    url: Optional[str] = Field(None, examples=["/OnlineJudge/api/v1/course/42"])
    join_url: Optional[str] = Field(
        None, examples=["/OnlineJudge/api/v1/course/42/join"]
    )
    quit_url: Optional[str] = Field(
        None, examples=["/OnlineJudge/api/v1/course/42/quit"]
    )
    html_url: Optional[str] = Field(None, examples=["/OnlineJudge/course/42"])


class ProblemsetType(Enum):
    contest = "contest"
    homework = "homework"
    exam = "exam"


class SubmissionLanguage(Enum):
    cpp = "cpp"
    python = "python"
    git = "git"
    verilog = "verilog"
    quiz = "quiz"


class SubmissionStatus(Enum):
    accepted = "accepted"
    wrong_answer = "wrong_answer"
    compile_error = "compile_error"
    runtime_error = "runtime_error"
    time_limit_exceeded = "time_limit_exceeded"
    memory_limit_exceeded = "memory_limit_exceeded"
    disk_limit_exceeded = "disk_limit_exceeded"
    memory_leak = "memory_leak"
    pending = "pending"
    compiling = "compiling"
    judging = "judging"
    void = "void"
    aborted = "aborted"
    skipped = "skipped"
    system_error = "system_error"
    bad_problem = "bad_problem"
    unknown_error = "unknown_error"


class Next(RootModel[Optional[str]]):
    root: Optional[str] = Field(
        None,
        description="下一页的地址，最后一页为 null",
        examples=["/OnlineJudge/api/v1/endpoint?cursor=42"],
    )


class Scope(Enum):
    user_profile = "user:profile"
    problem_read = "problem:read"
    submission_read = "submission:read"
    submission_create = "submission:create"
    submission_write = "submission:write"
    course_read = "course:read"
    course_membership = "course:membership"
    problemset_read = "problemset:read"
    problemset_membership = "problemset:membership"


class Problem(BaseModel):
    id: Optional[int] = Field(None, examples=[1000])
    title: Optional[str] = Field(None, examples=["A+B"])
    description: Optional[str] = Field(None, description="题目描述")
    input: Optional[str] = Field(None, description="输入格式")
    output: Optional[str] = Field(None, description="输出格式")
    examples: Optional[List[Example]] = Field(None, description="样例（新版）")
    example_input: Optional[str] = Field(None, description="样例输入")
    example_output: Optional[str] = Field(None, description="样例输出")
    data_range: Optional[str] = Field(None, description="数据范围")
    languages_accepted: Optional[List[SubmissionLanguage]] = Field(
        None, description="允许提交的语言"
    )
    allow_public_submissions: Optional[bool] = Field(
        None, description="是否允许公开代码"
    )


class Submission(BaseModel):
    id: Optional[int] = Field(None, examples=[42])
    friendly_name: Optional[str] = Field(
        None, description="提交者昵称", examples=["ACM"]
    )
    problem: Optional[ProblemBrief] = None
    public: Optional[bool] = Field(None, description="代码是否公开可见")
    language: Optional[SubmissionLanguage] = None
    score: Optional[int] = Field(None, examples=[100])
    message: Optional[str] = None
    details: Optional[Dict[str, Any]] = Field(
        None, description="评测点详情。格式可能在未来变动，请以 API 实际返回值为准。"
    )
    time_msecs: Optional[int] = Field(None, examples=[2233])
    memory_bytes: Optional[int] = Field(None, examples=[1048576])
    status: Optional[SubmissionStatus] = None
    should_show_score: Optional[bool] = Field(
        None,
        description="是否应该显示分数（如评测未完成、中止、分数无效等情况不应显示分数）",
    )
    created_at: Optional[datetime] = None
    code_url: Optional[str] = Field(
        None, examples=["/OnlineJudge/oj-submissions/42.code?X-Amz-Algorithm=..."]
    )
    abort_url: Optional[str] = Field(
        None,
        description="若不能中止，则为 null",
        examples=["/OnlineJudge/api/v1/submission/42/abort"],
    )
    html_url: Optional[str] = Field(None, examples=["/OnlineJudge/code/42/"])


class SubmissionBrief(BaseModel):
    id: Optional[int] = Field(None, examples=[42])
    friendly_name: Optional[str] = Field(
        None, description="提交者昵称", examples=["ACM"]
    )
    problem: Optional[ProblemBrief] = None
    status: Optional[SubmissionStatus] = None
    language: Optional[SubmissionLanguage] = None
    created_at: Optional[datetime] = None
    url: Optional[str] = Field(
        None,
        description="若无权限访问则为 null",
        examples=["/OnlineJudge/api/v1/submission/42"],
    )
    html_url: Optional[str] = Field(
        None, description="若无权限访问则为 null", examples=["/OnlineJudge/code/42"]
    )


class Problemset(BaseModel):
    id: Optional[int] = Field(None, examples=[42])
    course: Optional[Course] = None
    name: Optional[str] = None
    description: Optional[str] = None
    allowed_languages: Optional[List[SubmissionLanguage]] = Field(
        None, description="计入分数的语言"
    )
    start_time: Optional[datetime] = None
    end_time: Optional[datetime] = None
    late_submission_deadline: Optional[datetime] = Field(
        None, description="null 表示不允许迟交"
    )
    type: Optional[ProblemsetType] = None
    problems: Optional[List[ProblemBrief]] = None
    url: Optional[str] = Field(None, examples=["/OnlineJudge/api/v1/problemset/42"])
    join_url: Optional[str] = Field(
        None, examples=["/OnlineJudge/api/v1/problemset/42/join"]
    )
    quit_url: Optional[str] = Field(
        None, examples=["/OnlineJudge/api/v1/problemset/42/quit"]
    )
    html_url: Optional[str] = Field(None, examples=["/OnlineJudge/problemset/42"])
